CREATE DATABASE IF NOT EXISTS game CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS global CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'civcraft'@'%' IDENTIFIED BY 'civcraft';
GRANT ALL PRIVILEGES ON game.* TO 'civcraft'@'%';
GRANT ALL PRIVILEGES ON global.* TO 'civcraft'@'%';
FLUSH PRIVILEGES;
